"""本模块声明数据库、容器运行时、CLIProxyAPI 与代理目录的可替换端口。"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import datetime
from pathlib import Path
from typing import Protocol
from uuid import UUID

from account_pool.channels.cliproxyapi.client import AuthorizationStart
from account_pool.channels.cliproxyapi.suppliers.base import SupplierDefinition
from account_pool.domain import (
    EnvironmentConfiguration,
    EnvironmentRecord,
    GatewayEnvironment,
    OAuthCallback,
    ProxyProfile,
    SupplierKind,
)
from account_pool.policies import AccountPolicy
from account_pool.settings import AccountPoolSettings


class EnvironmentRepository(Protocol):
    async def initialize(self) -> None: ...

    async def list(self) -> tuple[EnvironmentRecord, ...]: ...

    async def get(self, environment_id: UUID) -> EnvironmentRecord | None: ...

    async def find_by_oauth_state(self, state: str) -> EnvironmentRecord | None: ...

    async def find_by_operation_id(self, operation_id: str) -> EnvironmentRecord | None: ...

    async def consume_oauth_state(self, state: str, consumed_at: datetime) -> EnvironmentRecord | None: ...

    async def save(self, record: EnvironmentRecord) -> EnvironmentRecord: ...

    async def delete(self, environment_id: UUID) -> None: ...

    async def save_if_version(
        self,
        record: EnvironmentRecord,
        expected_version: int,
    ) -> EnvironmentRecord | None: ...

    async def update_environment(
        self,
        environment_id: UUID,
        expected_version: int,
        environment: EnvironmentRecord,
    ) -> EnvironmentRecord | None: ...


class EnvironmentRuntime(Protocol):
    async def provision(self, record: EnvironmentRecord) -> None: ...

    async def ensure_control_plane_connections(self, environment_id: UUID) -> None: ...

    async def set_running(self, record: EnvironmentRecord, running: bool) -> None: ...

    async def remove(self, record: EnvironmentRecord) -> None: ...

    async def remove_compose(self, record: EnvironmentRecord) -> None: ...

    async def remove_directory(self, environment_id: UUID) -> None: ...

    def environment_dir(self, environment_id: UUID) -> Path: ...


class EnvironmentChannel(EnvironmentRuntime, Protocol):
    def supplier(self, kind: SupplierKind) -> SupplierDefinition: ...

    async def close(self) -> None: ...

    async def start_authorization(self, record: EnvironmentRecord) -> AuthorizationStart: ...

    async def authorization_status(self, record: EnvironmentRecord, state: str) -> str: ...

    async def cancel_oauth_session(self, record: EnvironmentRecord, state: str) -> None: ...

    async def submit_callback(self, record: EnvironmentRecord, callback: OAuthCallback) -> None: ...

    async def read_account(self, record: EnvironmentRecord) -> EnvironmentRecord: ...

    async def data_plane_health_check(self, record: EnvironmentRecord) -> bool: ...

    async def apply_configuration(
        self, record: EnvironmentRecord, configuration: EnvironmentConfiguration
    ) -> None: ...

    def gateway(self, record: EnvironmentRecord) -> GatewayEnvironment: ...


class CLIProxyClient(Protocol):
    async def close(self) -> None: ...

    async def start_authorization(self, record: EnvironmentRecord, supplier: SupplierDefinition) -> AuthorizationStart: ...


    async def authorization_status(self, record: EnvironmentRecord, state: str) -> str: ...

    async def submit_callback(
        self, record: EnvironmentRecord, supplier: SupplierDefinition, callback: OAuthCallback
    ) -> None: ...

    async def read_account(self, record: EnvironmentRecord, supplier: SupplierDefinition) -> EnvironmentRecord: ...

    async def data_plane_health_check(self, record: EnvironmentRecord) -> bool: ...

    async def set_credential_enabled(self, record: EnvironmentRecord, enabled: bool) -> None: ...

    async def set_proxy_url(self, record: EnvironmentRecord, proxy_url: str) -> None: ...

    async def set_enabled_models(self, record: EnvironmentRecord, enabled_models: Sequence[str]) -> None: ...

    async def apply_configuration(
        self, record: EnvironmentRecord, supplier: SupplierDefinition, configuration: EnvironmentConfiguration
    ) -> None: ...

    async def apply_global_settings(self, record: EnvironmentRecord, settings: AccountPoolSettings) -> None: ...

    async def apply_policy(self, record: EnvironmentRecord, policy: AccountPolicy) -> None: ...

    async def list_plugins(self, record: EnvironmentRecord) -> Mapping[str, object]: ...

    async def list_plugin_store(self, record: EnvironmentRecord) -> Mapping[str, object]: ...

    async def install_plugin(self, record: EnvironmentRecord, plugin_id: str, version: str) -> Mapping[str, object]: ...

    async def set_plugin_enabled(
        self, record: EnvironmentRecord, plugin_id: str, enabled: bool
    ) -> Mapping[str, object]: ...

    async def uninstall_plugin(self, record: EnvironmentRecord, plugin_id: str) -> Mapping[str, object]: ...

    async def get_plugin_config(self, record: EnvironmentRecord, plugin_id: str) -> Mapping[str, object]: ...

    async def put_plugin_config(
        self, record: EnvironmentRecord, plugin_id: str, config: Mapping[str, object]
    ) -> Mapping[str, object]: ...

    async def upload_auth_file(
        self, record: EnvironmentRecord, filename: str, content: bytes, content_type: str | None
    ) -> None: ...

    async def download_auth_file(self, record: EnvironmentRecord, filename: str) -> tuple[bytes, str]: ...

    async def delete_auth_file(self, record: EnvironmentRecord, filename: str) -> None: ...

    async def patch_auth_file_status(
        self, record: EnvironmentRecord, filename: str, auth_index: str | None, disabled: bool
    ) -> None: ...

    async def patch_auth_file_fields(
        self, record: EnvironmentRecord, filename: str, fields: Mapping[str, object]
    ) -> None: ...

    async def get_auth_file_models(self, record: EnvironmentRecord, filename: str) -> tuple[str, ...]: ...


class ProxyProfileRepository(Protocol):
    async def list(self) -> tuple[ProxyProfile, ...]: ...

    async def get_url(self, profile_id: str) -> str | None: ...

    async def upsert_gateways(self, gateways: Sequence[tuple[str, str, str]]) -> int: ...
